// Generated by CoffeeScript 1.7.1
(function() {
  var checkLoginState, statusChangeCallback, testAPI;

  statusChangeCallback = function(response) {
    console.log("statusChangeCallback");
    console.log(response);
    if (response.status === "connected") {
      testAPI();
    } else if (response.status === "not_authorized") {

    } else {

    }
  };

  checkLoginState = function() {
    FB.getLoginStatus(function(response) {
      statusChangeCallback(response);
    });
  };

  testAPI = function() {
    console.log("Welcome!  Fetching your information.... ");
    FB.api("/me", function(response) {
      console.log("Good to see you, " + response.name + ".");
    });
  };

  window.fbAsyncInit = function() {
    FB.init({
      appId: "237755086432090",
      cookie: true,
      xfbml: true,
      version: "v2.0"
    });
    FB.getLoginStatus(function(response) {
      statusChangeCallback(response);
    });
  };

  (function(d, s, id) {
    var fjs, js;
    js = void 0;
    fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) {
      return;
    }
    js = d.createElement(s);
    js.id = id;
    js.src = "//connect.facebook.net/en_US/sdk.js";
    fjs.parentNode.insertBefore(js, fjs);
  })(document, "script", "facebook-jssdk");

}).call(this);
